# Generated by Django 5.0.3 on 2024-06-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('automate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats', to='AutomateApp.automate')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquette', models.CharField(blank=True, default='', max_length=100)),
                ('is_epsilon_transition', models.BooleanField(blank=True, default=False, null=True)),
                ('etat_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_arrivee', to='AutomateApp.etat')),
                ('etat_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_depart', to='AutomateApp.etat')),
            ],
        ),
    ]
